/**
 * Local project data — MRAX experiments, ZYETA professional work, and developer tools.
 * Sourced from ~/Projects/personal/ and ~/Projects/zyeta/ on the local filesystem.
 * Tech stacks verified from actual package.json / requirements.txt files.
 */
import type { Project } from './data';

export const localProjects: Project[] = [
  // ── MRAX Experiments (~/Projects/personal/mrax/) ──────────────────

  {
    id: 'mrax-kanban',
    title: 'MRAX Kanban',
    description: 'Drag-and-drop kanban board exploring MRAX architecture',
    longDescription:
      'A fully-featured kanban board with drag-and-drop, custom columns, priority levels, assignees, and due dates. Exploring MRAX architecture patterns through a zero-dependency vanilla JavaScript implementation with IndexedDB persistence. No build step — open index.html directly.',
    thumbnail: '',
    icon: '📋',
    gradient: 'linear-gradient(150deg, #fbbf24 0%, #f59e0b 50%, #92400e 100%)',
    screenshots: [],
    techStack: ['Vanilla JavaScript', 'IndexedDB', 'HTML5 Drag & Drop', 'CSS Modules'],
    category: 'experiment',
    githubUrl: 'https://github.com/rdtect/mrax-kanban',
    featured: false,
    dateAdded: '2025-06-01',
    source: 'local',
  },
  {
    id: 'mrax-solitaire',
    title: 'MRAX Solitaire',
    description: 'Klondike solitaire with unlimited undo and keyboard shortcuts',
    longDescription:
      'A complete Klondike Solitaire card game built with zero dependencies. Features drag-and-drop card movement, unlimited undo (50 moves), keyboard shortcuts (Ctrl+Z, N for new game), move counter, timer, and win detection. Exploring MRAX state management patterns with pure JavaScript.',
    thumbnail: '',
    icon: '🃏',
    gradient: 'linear-gradient(135deg, #dc2626 0%, #991b1b 40%, #7f1d1d 100%)',
    screenshots: [],
    techStack: ['Vanilla JavaScript', 'CSS Animations', 'localStorage', 'ES6 Modules'],
    category: 'experiment',
    githubUrl: 'https://github.com/rdtect/mrax-solitaire',
    featured: false,
    dateAdded: '2025-05-01',
    source: 'local',
  },
  {
    id: 'mrax-tictactoe',
    title: 'MRAX Tic-Tac-Toe',
    description: 'Cross-platform game — same MRAX logic in Python and Svelte',
    longDescription:
      'A cross-platform architecture demonstration showing identical game logic (GameState, Rules, Actions) implemented in both Python (terminal) and TypeScript (Svelte web). The Model layer is byte-for-byte equivalent across platforms — only the Experience layer (terminal I/O vs DOM events) differs. Documents the MRX pattern side-by-side.',
    thumbnail: '',
    icon: '⭕',
    gradient: 'linear-gradient(135deg, #84cc16 0%, #65a30d 40%, #3f6212 100%)',
    screenshots: [],
    techStack: ['Python 3', 'SvelteKit', 'TypeScript', 'Web Audio API', 'MRAX Pattern'],
    category: 'experiment',
    githubUrl: 'https://github.com/rdtect/mrax-tictactoe',
    featured: true,
    dateAdded: '2025-04-01',
    source: 'local',
  },
  {
    id: 'mrax-todo',
    title: 'MRAX Todo',
    description: 'Enhanced to-do app with filters, stats, and IndexedDB',
    longDescription:
      'An enhanced to-do application with filter system (all/active/completed), live statistics, smooth animations, and dark theme. Built with zero dependencies to explore MRAX State/Rules/Actions separation. Uses IndexedDB for persistence with a clean modular architecture.',
    thumbnail: '',
    icon: '✅',
    gradient: 'linear-gradient(135deg, #facc15 0%, #ca8a04 40%, #854d0e 100%)',
    screenshots: [],
    techStack: ['Vanilla JavaScript', 'IndexedDB', 'CSS Animations', 'ES6 Modules'],
    category: 'experiment',
    githubUrl: 'https://github.com/rdtect/mrax-todo',
    featured: false,
    dateAdded: '2025-05-15',
    source: 'local',
  },

  // ── Developer Tools (~/Projects/personal/) ────────────────────────

  {
    id: 'ai-ecosystem',
    title: 'AI Ecosystem',
    description: 'AI development environment with Ollama, n8n, ChromaDB, and MCP',
    longDescription:
      'Comprehensive AI-powered development environment integrating Claude Code, Gemini CLI, OpenCode CLI, MCP servers, n8n workflows, and OpenWebUI. Includes Docker configs for self-hosted AI services on a VPS, memory structures, system prompts, and agentic framework documentation. The operational backbone behind all AI-assisted development.',
    thumbnail: '',
    icon: '🧠',
    gradient: 'linear-gradient(135deg, #818cf8 0%, #4f46e5 40%, #312e81 100%)',
    screenshots: [],
    techStack: ['Docker', 'Shell Scripts', 'n8n', 'Ollama', 'ChromaDB', 'MCP Servers'],
    category: 'tool',
    featured: false,
    dateAdded: '2025-01-01',
    source: 'local',
  },
  {
    id: 'everything-claude-code',
    title: 'Everything Claude Code',
    description: 'Battle-tested Claude Code configs — agents, skills, hooks, commands',
    longDescription:
      'A production-ready collection of Claude Code configurations battle-tested across 10+ months of real product builds. Includes 12 agents (architect, council, planner, designer, security-reviewer, and more), 9 slash commands, skills, hooks, rules, and MCP server configs. Originally from an Anthropic hackathon winner.',
    thumbnail: '',
    icon: '🔮',
    gradient: 'linear-gradient(135deg, #f97316 0%, #c2410c 40%, #7c2d12 100%)',
    screenshots: [],
    techStack: ['Claude Code', 'Markdown', 'YAML', 'Shell', 'MCP Protocol'],
    category: 'oss',
    githubUrl: 'https://github.com/rdtect/everything-claude-code',
    featured: true,
    dateAdded: '2025-02-01',
    source: 'local',
  },
  {
    id: 'vault-indexer',
    title: 'Vault Indexer',
    description: 'Index Obsidian vault into ChromaDB with semantic embeddings',
    longDescription:
      'Python script that indexes an Obsidian vault into a remote ChromaDB instance with semantic embeddings. Uses all-MiniLM-L6-v2 ONNX model for local CPU-bound embedding generation, chunks markdown at 1000 chars with 200-char overlap, and batch-uploads to ChromaDB at chroma.rdtect.com via Bearer auth. Enables semantic search across the entire knowledge base.',
    thumbnail: '',
    icon: '🔍',
    gradient: 'linear-gradient(135deg, #34d399 0%, #047857 40%, #064e3b 100%)',
    screenshots: [],
    techStack: ['Python 3.13', 'ChromaDB', 'ONNX Runtime', 'all-MiniLM-L6-v2', 'Markdown'],
    category: 'tool',
    featured: false,
    dateAdded: '2025-03-01',
    source: 'local',
  },

  // ── ZYETA Professional Work (~/Projects/zyeta/) ───────────────────

  {
    id: '2gethr-jingle-hunt',
    title: '2gethr Jingle Hunt',
    description: 'Team jingle hunt game with QR scanning and AI features',
    longDescription:
      'An interactive team jingle/scavenger hunt game built for live events. Features QR code scanning and generation, AI-powered game mechanics, SQLite persistence via Drizzle ORM, and PDF certificate export. Includes ngrok integration for public tunnel access during events and HTTPS dev support.',
    thumbnail: '',
    icon: '🎵',
    gradient: 'linear-gradient(135deg, #fbbf24 0%, #dc2626 40%, #991b1b 100%)',
    screenshots: [],
    techStack: ['SvelteKit 2', 'Svelte 5', 'TypeScript', 'Tailwind CSS 4', 'Drizzle ORM', 'SQLite', 'OpenAI', 'html5-qrcode'],
    category: 'professional',
    githubUrl: 'https://github.com/rdtect/2gethr-jingle-hunt',
    featured: false,
    dateAdded: '2024-12-01',
    source: 'local',
  },
  {
    id: 'aero-window',
    title: 'Aero Window',
    description: 'Circadian rhythm airplane window with 3D globe and AI',
    longDescription:
      'An immersive airplane window simulation combining Three.js 3D scene rendering, CesiumJS geospatial globe visualization, and Google Gemini AI. Built with Threlte (Svelte bindings for Three.js) for declarative 3D. Features procedural texture generation and AI-driven interactions in a purely frontend architecture.',
    thumbnail: '',
    icon: '✈️',
    gradient: 'linear-gradient(135deg, #38bdf8 0%, #0284c7 40%, #075985 100%)',
    screenshots: [],
    techStack: ['SvelteKit 2', 'Svelte 5', 'Three.js', 'Threlte', 'CesiumJS', 'Google Gemini', 'TypeScript'],
    category: 'professional',
    githubUrl: 'https://github.com/zyetaone/swa_window',
    featured: true,
    dateAdded: '2025-01-15',
    source: 'local',
  },
  {
    id: 'ai-pm-assessor',
    title: 'AI PM Assessor',
    description: 'AI-powered project manager skills assessment platform',
    longDescription:
      'An AI-driven PM skills assessment platform where trainees upload BOQ Excel spreadsheets from construction/AV projects and AI generates quiz questions from the data. Evolved through 5 iterations — from vanilla Lit SPA to a full agentic Cloudflare-deployed LMS with authentication, certificates, gamification, and RAG pipeline. The latest version uses reactive domain actors powered by Svelte 5 runes.',
    thumbnail: '',
    icon: '🎓',
    gradient: 'linear-gradient(135deg, #c084fc 0%, #9333ea 40%, #6b21a8 100%)',
    screenshots: [],
    techStack: ['SvelteKit 2', 'Svelte 5', 'Drizzle ORM', 'Cloudflare D1', 'Google Gemini', 'Zod', 'bits-ui', 'Wrangler'],
    category: 'ai',
    featured: true,
    dateAdded: '2024-10-01',
    source: 'local',
  },
  {
    id: 'dualsync',
    title: 'DualSync',
    description: 'Synchronized multi-panel browser for OpenSpace.ai',
    longDescription:
      'A suite of Electron desktop apps for synchronizing multiple browser panels viewing the OpenSpace.ai collaborative workspace. Evolved from dual-panel to quad-panel to a pro version combining SvelteKit UI with Electron wrapping. Features hybrid sync (native horizontal + API/mouse vertical), cross-platform builds, and WSL compatibility.',
    thumbnail: '',
    icon: '🔄',
    gradient: 'linear-gradient(135deg, #94a3b8 0%, #475569 40%, #1e293b 100%)',
    screenshots: [],
    techStack: ['Electron', 'SvelteKit 2', 'Svelte 5', 'TypeScript', 'Electron Forge', 'Vite', 'Vitest', 'Playwright'],
    category: 'tool',
    featured: false,
    dateAdded: '2024-08-01',
    source: 'local',
  },
  {
    id: 'dx-platform',
    title: 'DX Platform',
    description: 'ZYETA digital experience platform with ROI calculator and AV showcase',
    longDescription:
      'The corporate website for ZYETA Technologies — a digital experience platform that transforms physical spaces into intelligent digital experiences via "ZYETAi" behavioral prediction AI. Features an interactive ROI Calculator, AV Showcase, glassmorphism design system, rich text editor (TipTap), full auth stack (Lucia + Argon2), and RBAC. The website IS the experience.',
    thumbnail: '',
    icon: '💎',
    gradient: 'linear-gradient(135deg, #e879f9 0%, #c026d3 40%, #86198f 100%)',
    screenshots: [],
    techStack: ['SvelteKit 2', 'Svelte 5', 'TypeScript', 'Tailwind CSS 4', 'Drizzle ORM', 'SQLite', 'Lucia Auth', 'TipTap', 'Vitest'],
    category: 'professional',
    featured: true,
    dateAdded: '2024-09-01',
    source: 'local',
  },
  {
    id: 'meddicc-research-app',
    title: 'MEDDICC Research',
    description: 'AI-powered MEDDICC sales qualification analysis tool',
    longDescription:
      'An AI-powered MEDDICC sales qualification tool with two modes: Research Mode (deep company analysis producing full MEDDICC reports with executive overview, sector lens, and strategic recommendations) and Insight Mode (thematic industry trend analysis). Uses a Triple Diamond architecture with n8n-orchestrated AI workflows and Server-Sent Events for real-time streaming results. Includes visual flowchart views via Svelte Flow.',
    thumbnail: '',
    icon: '📊',
    gradient: 'linear-gradient(135deg, #fb7185 0%, #e11d48 40%, #881337 100%)',
    screenshots: [],
    techStack: ['SvelteKit 2', 'Svelte 5', 'TypeScript', 'Tailwind CSS 4', 'Drizzle ORM', 'PostgreSQL', 'n8n', 'SSE', 'Svelte Flow'],
    category: 'ai',
    githubUrl: 'https://github.com/rdtect/z-meddicc',
    featured: true,
    dateAdded: '2024-11-01',
    source: 'local',
  },
  {
    id: 'workspace-studio',
    title: 'Workspace Studio',
    description: 'AI-powered interactive workshop platform with 3D world and inpainting',
    longDescription:
      'An interactive workshop/seminar platform where participants take a personality quiz, use AI image editing with mask/inpainting tools (draw, brush, magic wand, polygon), and see results in a 3D isometric world scene with floating islands. Combines Cloudflare Workers + D1 + R2, Fal.ai (Flux Inpainting + Nano Banana Pro), Three.js via Threlte, and version-tree branching edit history. The most architecturally ambitious ZYETA project.',
    thumbnail: '',
    icon: '🏗️',
    gradient: 'linear-gradient(135deg, #2dd4bf 0%, #0891b2 40%, #155e75 100%)',
    screenshots: [],
    techStack: ['SvelteKit 2', 'Svelte 5', 'TypeScript', 'Tailwind CSS 4', 'Three.js', 'Threlte', 'Fal.ai', 'Cloudflare D1', 'Cloudflare R2', 'Drizzle ORM', 'Valibot'],
    category: 'professional',
    featured: true,
    dateAdded: '2025-01-01',
    source: 'local',
  },
];
